# Generated by Django 4.0.5 on 2022-06-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ano_Solicitud', models.TextField(max_length=500, null=True)),
                ('ID_SGI', models.TextField(max_length=500, null=True)),
                ('Zona', models.TextField(null=True)),
            ],
            options={
                'db_table': 'capacidad',
            },
        ),
    ]
