# Generated by Django 4.0.5 on 2022-06-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capacidades_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacidad',
            name='Zona',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
