# Generated by Django 4.0.5 on 2022-06-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capacidades_App', '0002_alter_capacidad_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidad',
            name='Asignacion_Energía',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Cantidad_N',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Clase_Zona_Roja',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Clave',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Clientes_Afectados',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Comuna',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Cuadrantes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='EPS',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Estado_Asignación_Energía',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Estado_CaPO',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Estado_Design_Simplificado',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Estado_Ejecucion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Estado_Ejecucion_2',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Fecha_Cancelado',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Fecha_Comunicacion_EPS',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Fecha_Design',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Fecha_Ejecucion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Fecha_Estado',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Fecha_Solicitud',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='HUB',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Horas_90',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Horas_95',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='KPI_DESIGN',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='KPI_EJECUCION',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='MES_Ejecucion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Mes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Mes_Ejecucion_2',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Mes_Sol',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Motivo',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='OBS_Solicitud',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Obras_Complementarias',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Observaciones_CaPO',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Responsable',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Semana_Ejecucion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Sol2',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Tipo_Solucion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Tipo_de_Red',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='W_Solicitud',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Year',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Year_2022',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Year_Ejecucion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='capacidad',
            name='Zona_Roja',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
